apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: tenant-gitops
  name: tenant-b-team-sockshop-app
  namespace: tenant-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-b-team-sockshop
  project: b-team
  source:
    path: b-team/sockshop
    repoURL: https://github.com/caseyrobb/tenant-repos
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
