apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-scan-run
spec:
  pipelineRef:
    name: build-and-scan
  params:
  - name: deployment-name
    value: pipelines-vote-api
  - name: git-url
    value: https://github.com/openshift/pipelines-vote-api.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/devsecops/pipelines-vote-api
  - name: rox_central_endpoint
    value: roxsecrets
  - name: rox_api_token
    value: roxsecrets  
  - name: output_format
    value: table
  serviceAccountName: devsecops
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
