apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2025-03-13T15:43:16Z"
  name: system:openshift:scc:anyuid
  namespace: devsecops
  resourceVersion: "7460257"
  uid: 6e5df242-9f75-4607-8af3-0711ffe53046
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: devsecops
  namespace: devsecops
