apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2025-03-13T15:43:32Z"
  name: system:openshift:scc:privileged
  namespace: devsecops
  resourceVersion: "7460437"
  uid: 5fd76249-c38e-47cf-85d6-aaa01b6d957b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: devsecops
  namespace: devsecops
