apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devsecops
resources:
- build-and-scan-pipeline.yaml
- build-and-scan-pipelinerun.yaml
- buildah-task.yaml
- devsecops-admin-rb.yaml
- devsecops-anyuid-scc-crb.yaml
- devsecops-privileged-scc-crb.yaml
- git-clone-task.yaml
- rox-deployment-check-task.yaml
- rox-image-check-task.yaml
- rox-image-scan-task.yaml
#- roxsecrets.yaml
- serviceaccount.yaml
