apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-config
  namespace: tenant-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - team: a-team
        - team: b-team
  template:
    metadata:
      name: 'tenant-{{.team}}-config'
    spec:
      project: '{{.team}}'
      source:
        repoURL: https://github.com/caseyrobb/cluster-config
        targetRevision: HEAD
        path: 'tenants/overlays/{{.team}}'
      destination:
        server: https://kubernetes.default.svc 
        namespace: 'tenant-{{.team}}-config
