apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: tenant-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - team: a-team
          appname: guestbook
        - team: a-team
          appname: sockshop
        - team: b-team
          appname: sockshop
  template:
    metadata:
      name: 'tenant-{{.team}}-{{.appname}}'
    spec:
      project: '{{.team}}'
      source:
        repoURL: https://github.com/caseyrobb/cluster-config
        targetRevision: tenant-onboarding
        path: 'tenants/{{.team}}/apps/{{.appname}}'
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: argoproj.io
        kind: Application
        jsonPointers:
          - /metadata/labels
      syncOptions:
        automated:
          selfHeal: true
          prune: true
