apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-config
  namespace: tenant-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - team: a-team
          appname: guestbook
        - team: a-team
          appname: sockshop
        - team: b-team
          appname: sockshop
  template:
    metadata:
      name: 'tenant-{{.team}}-{{.appname}}'
      labels:
        app.kubernetes.io/instance: tenant-gitops
    spec:
      project: '{{.team}}'
      source:
        repoURL: https://github.com/caseyrobb/cluster-config
        targetRevision: tenant-onboarding
        path: 'tenants/{{.team}}/{{.appname}}'
      destination:
        server: https://kubernetes.default.svc
