apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-security
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  source:
    path: PATCH_ME
    repoURL: https://github.com/caseyrobb/cluster-config/
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
