apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpasswd
  namespace: openshift-config
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: 1104422b-e7bb-408d-84bc-5d23993f2bb6
      metadataPolicy: None
      property: password
    secretKey: htpasswd
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: passbolt
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: htpasswd
