apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-configuration-operator
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: PATCH_ME
    repoURL: https://github.com/caseyrobb/cluster-config/
    targetRevision: tenant-onboarding
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
