kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: elasticsearch-eck-operator-certified
      namespace: openshift-operators
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
