kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: 'components/apps/container-security-operator/overlays/stable-3.13'
    target:
      kind: Application
      name: container-security-operator
      namespace: openshift-gitops
