kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: 'components/apps/openshift-gitops/overlays/latest'
    target:
      kind: Application
      name: openshift-gitops-operator
      namespace: openshift-gitops
