apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAihYmtKZa4YFpfTOSTW8dednbLBmcvtpQm4qltT47P5W5PsE18eEu21Ohy48zaaJMvz8Et93u4W2rnl+NKbaV33ZMddqoRZn1Bypb8Rv1lZDzQAEFA0LZuHtPYutUY8Q4HUNnW2YQaL4PcNxU3/lbEO5cv6Np0r625na0IxPHAusqv0j6htXXl6Wfnu9tD3nKdhixdubNN7XQGUWhBm51dx1MTYkenXJSv9jCgde692Q/0wH0kT79wne0YObuQ2X1FeddSlLnsFjMe/syaQT/inixiRgKDEA5USq4GgsmM8YnIIYm49tFGxUv7P6CzGhDIppw+O+TP78+ITQhfMqXe+QZdEL8AiT6Ihzesj049WCXUsGhL0NeWeZGolEr2NvXIYO/oPOfQgRJI21K37I/koop9GfJnbgVb2PrTQMzDgJMWv6cTyVXdVz8HRu5pjXH0ygqjvYy5EvYSr5Oay8ErBjHyHFdyVwTINKORBrgVF3jE/k6lLPgINuak/kLegu6dTpA6sIaLV8t7pK0TebqkiKZ5z2mqbH+ZtWxRxsn7K64iLRpx8MA+OiS6UyPyJHoujF5J8nePy2+oOmiqdbzmYQ8fxzyDPFePm6HMH1FfYq7aw+j4HSZI8lq9sGeBE2rR2eJFknlHWtjP29Rvkp5EigZeW3MxN4bxTjNvlmPS3byyJPR/snf/g0I48bJd3AdntWY6nB5UT5uabO4Awtw3Yott1XA1CGsQCOCGEF1FPDmvCbhaJXMcKA+hZ4oVF4T8FQhsPlvtk3zeCKV/+Zli/tSWVAXuOcD5N3DaFfE2BZFDeNZKdj88cFA9YIZmt27xoarimRVW5MR8qyXpa51OelxKX201FqZnnrni7mc3gB/IeL5ltH2FEHtAbsksj/YjX1zraId0wPOrSSsCVVxw3Q==
  template:
    metadata:
      name: htpasswd-secret
      namespace: openshift-config
