apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  labels:
    app.kubernetes.io/instance: cluster-config-oauth
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
  name: cluster
spec:
  identityProviders: []
