apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: PATCH_ME
    repoURL: https://github.com/caseyrobb/cluster-config/
    targetRevision: HEAD
  project: default
  ignoreDifferences:
  - group: "v1"
    kind: "Secret"
    name: "v4-0-config-user-idp-0-file-data"
    namespace: openshift-authentication
    jqPathExpressions:
      - .
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
