apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-example
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/caseyrobb/cluster-config
    path: components/apps/grafana-example
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
