apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ''
  replicas: 3
  tuningOptions: {}
  unsupportedConfigOverrides: null
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      value: reserved
