apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: ingress-cert
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ''
  replicas: 3
  tuningOptions: {}
  unsupportedConfigOverrides: null
