kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: grafana-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'v4'
