apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: c-team
  namespace: tenant-gitops
spec:
  description: C-team project
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  roles:
  - groups:
    - c-team
    name: c-team-admin
    policies:
    - p, proj:c-team:c-team-admin, applications, *, c-team/*, allow
  sourceRepos:
  - https://github.com/caseyrobb/cluster-config
  - https://github.com/caseyrobb/tenant-repos
