kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: 'components/apps/clusterversion/overlays/4.17.18'
    target:
      kind: Application
      name: clusterversion
      namespace: openshift-gitops
