apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: components/apps/openshift-oauth
    repoURL: https://github.com/caseyrobb/cluster-config/
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
