apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  encryption:
    type: aescbc
  servingCerts:
    namedCertificates:
    - names:
      - api.ocp.redcomet.ca
      servingCertificate:
        name: api-cert
