apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- user-ca-bundle-cm.yaml
- api-certificate-sealedsecret.yaml
- ingress-wildcard-sealedsecret.yaml
- cluster-apiserver.yaml
- cluster-proxy.yaml
- default-ingresscontroller.yaml
#- patch-apiserver-job.yaml
#- patch-ingress-job.yaml
#- patch-proxy-job.yaml
