apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api-cert-sealedsecret.yaml
- ingress-cert-sealedsecret.yaml
- custom-ca-cm.yaml
- cluster-proxy.yaml
- cluster-apiserver.yaml
#- default-ingresscontroller.yaml
#- patch-apiserver-job.yaml
#- patch-ingress-job.yaml
#- patch-proxy-job.yaml
