apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: team-a-repo
  namespace: tenant-gitops
type: Opaque
stringData:
  name: team-a-repo
  project: team-a
  type: git
  url: https://github.com/caseyrobb/tenant-repos
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: team-a-cluster-config-repo
  namespace: tenant-gitops
type: Opaque
stringData:
  name: cluster-config-repo
  project: team-a
  type: git
  url: https://github.com/caseyrobb/cluster-config
