apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vault
    helm:
      parameters:
      - name: global.namespace
        value: vault
      - name: global.openshift
        value: "true"
      - name: server.ha.replicas
        value: "1"
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

