apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Grafana.v1alpha1.integreatly.org,GrafanaDashboard.v1alpha1.integreatly.org,GrafanaDataSource.v1alpha1.integreatly.org,GrafanaFolder.v1alpha1.integreatly.org,GrafanaNotificationChannel.v1alpha1.integreatly.org
  name: grafana
  namespace: grafana
spec:
  targetNamespaces:
  - grafana
  upgradeStrategy: Default
