apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../components/argocd/it-tools

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: 'environments/dev/apps/it-tools'
    target:
      kind: Application
      name: it-tools
      namespace: openshift-gitops
