apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/aggregate/default

patches:
  - target:
      kind: Subscription
      name: rhacs-operator
      namespace: rhacs-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'latest'
