apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAXFIZW0Oai6tMoDG144A5VgHybyUjkw+DWtXJbNbHgRDnX40oXi/Zt4ZlyjGuPgfOGUSF1aA+8pb0op2uE/pwT1yeAO+dfW2kQ80FXhPRmEtugeVt06h3FuSxA/g51jaM8PdV8z3d6hx2ZVaq7bZDoSe/7gy1Zf0x3DL1B0olHE/XzKE5gYYBXtFoEQFONaJUtoRSO2zCTDu78nJ1It5NTBLtHn0CUZwOVrrhLPp8C+e+PqV6b5GKByHxMjXrCDsbR02jeKJOyzflmTkOPuGdajOGHtoptwnf4SOJAeVAZW7hYQG98iiWfDKV9NOrhBykcWST16kL2iIkofO4JDZExUH5nxjESIztSxNYD2moiQS6LlHMVZ/w1AnsoisUjrLKHyKMm/SdstM8IDZ6YU1pXZ6nHh/ea5YIxgWU6KLPNkOuBWV7CUWkkT9U+0GXQF0VmtY4Rw6H3BeHo1oh19hIsNgLYRjQwge6Kzq2j1fyNw4abKbmjRj02m3/Y/pNCgJiQE/8aLeUFEAddb5rLeKRnDRwBGfnXtQOBQjf2UdG+CMCJVol1KXVqbLY5SCXGNqkVcFAkEtjEyVz3hJJyJnR5i+d9boMOnAG68Xtl03N0TglDm5rpvY96Sw2owDb/I5nJK8Dw8w1d9hCP34IZ7DkayNdalA1+P9Pvc5mR8mf55IRm5Y2/42iXcfIOhi+UuuxYiTW7iKw4gu2Q6K0lH/rl7FvC85zC8ng1+kUftIcYOFpVRPz4dRcrmWfwVO6Ah5DBs92WrLO0rEi5BuNddHHn840i9VQ2kK5x8QeqgRAD4+raqBS4kguwlyFW5rpRkv7Y8hgoCUAidxoYt8zjmvA97I6sLK6xuBYSZ6t7NQ5b8MbrfmNIlFgz8MDkntckDv6S6IQyLBIrZdLZ/bu5B+onlgPZE+bBpU9Mc3xiEBHZLo3b+caX/9wJc+Sz+8YnwlTfWG3XfFCB0RXYRh3kISs=
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd-secret
      namespace: openshift-config

