apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  labels:
    app.kubernetes.io/instance: cluster-config-authentication
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: HTPasswd
    type: HTPasswd
  - mappingMethod: claim
    name: rhsso
    openID:
      ca:
        name: openid-ca-xb8db
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: openshift
      clientSecret:
        name: openid-client-secret-gdhvc
      issuer: https://keycloak-rhsso.apps.ocp.redcomet.ca/auth/realms/openshift
    type: OpenID
