apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  labels:
    app.kubernetes.io/instance: cluster-config-authentication
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: HTPasswd
    type: HTPasswd
  - name: rhsso
    mappingMethod: claim
    openID:
      ca:
        name: openid-ca-crt
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
      clientID: openshift
      clientSecret:
        name: openid-client-secret
      issuer: https://keycloak-rhsso.apps.ocp.redcomet.ca/auth/realms/openshift
    type: OpenID
