apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  labels:
    app.kubernetes.io/instance: cluster-config-authentication
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: HTPasswd
    type: HTPasswd
