apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp-m7zn5
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
  name: ocp-m7zn5-infra
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-m7zn5
      machine.openshift.io/cluster-api-machineset: ocp-m7zn5-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-m7zn5
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: ocp-m7zn5-infra
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          node-role.kubernetes.io: infra
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
      providerSpec:
        value:
          affinity_groups_names:
          - workers
          apiVersion: ovirtproviderconfig.machine.openshift.io/v1beta1
          auto_pinning_policy: none
          cluster_id: 17109ed4-4a40-11ed-b892-00163e3275f9
          cpu:
            cores: 4
            sockets: 2
            threads: 1
          credentialsSecret:
            name: ovirt-credentials
          id: ""
          kind: OvirtMachineProviderSpec
          memory_mb: 16384
          metadata:
            creationTimestamp: null
          name: ""
          os_disk:
            size_gb: 120
          template_name: ocp-m7zn5-rhcos
          type: server
          userDataSecret:
            name: worker-user-data
