kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'v5'
    target:
      kind: Subscription
      name: grafana-operator
      namespace: openshift-operators
