apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    redcomet.ca/team-name: a-team
  name: a-team
  namespace: tenant-gitops
spec:
  description: A-Team project
  destinations:
  - name: in-cluster
    namespace: tenant-a-team-*
    server: https://kubernetes.default.svc
  roles:
  - groups:
    - a-team
    name: a-team-admin
    policies:
    - p, proj:a-team:a-team-admin, applications, *, a-team/*, allow
  sourceRepos:
  - '*https://github.com/caseyrobb/tenant-repos'
