kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: 'components/apps/web-terminal/overlays/fast'
    target:
      kind: Application
      name: web-terminal
      namespace: openshift-gitops
