apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: it-tools-dev

resources:
  - ../../../../components/apps/it-tools

patches:
  - patch: |-
      - op: add
        path: /spec/host
        value: 'it-tools-dev.apps.cluster-qmznk.dynamic.redhatworkshops.io'
    target:
      kind: Route
      name: it-tools
