kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: 'components/apps/namespace-configuration-operator/overlays/default'
    target:
      kind: Application
      name: namespace-configuration-operator
      namespace: openshift-gitops
