apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: tenant-gitops-rbac
spec:
  labelSelector:
    matchLabels:
      redcomet.ca/tenant: "true"  
  templates:
  - objectTemplate: |  
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: argocd-application-controller-admin
        namespace: {{ .Name }}  
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - kind: ServiceAccount
        name: argocd-argocd-application-controller
        namespace: tenant-gitops
  - objectTemplate: |  
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: argocd-applicationset-controller-admin
        namespace: {{ .Name }}  
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - kind: ServiceAccount
        name: argocd-applicationset-controller
        namespace: tenant-gitops
---
