apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: sealed-secrets
    helm:
      parameters:
      - name: nameOverride
        value: controller
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.1
  - repoURL: https://github.com/caseyrobb/cluster-config
    path: components/apps/sealed-secrets
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
