apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    chart: sealed-secrets
    helm:
      parameters:
      - name: namespace
        value: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
